// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChromePath(arg1, arg2) {
  return window['go']['main']['App']['AddChromePath'](arg1, arg2);
}

export function CheckExtensionUpdates() {
  return window['go']['main']['App']['CheckExtensionUpdates']();
}

export function CheckHTTPParse(arg1) {
  return window['go']['main']['App']['CheckHTTPParse'](arg1);
}

export function CountNotes() {
  return window['go']['main']['App']['CountNotes']();
}

export function CreateRepeaterEntry(arg1, arg2) {
  return window['go']['main']['App']['CreateRepeaterEntry'](arg1, arg2);
}

export function CreateWaypoint(arg1, arg2) {
  return window['go']['main']['App']['CreateWaypoint'](arg1, arg2);
}

export function DeleteChromePath(arg1, arg2) {
  return window['go']['main']['App']['DeleteChromePath'](arg1, arg2);
}

export function DeleteRepeaterEntry(arg1) {
  return window['go']['main']['App']['DeleteRepeaterEntry'](arg1);
}

export function DeleteWaypoint(arg1) {
  return window['go']['main']['App']['DeleteWaypoint'](arg1);
}

export function DoExtender(arg1) {
  return window['go']['main']['App']['DoExtender'](arg1);
}

export function DownloadExtension(arg1, arg2) {
  return window['go']['main']['App']['DownloadExtension'](arg1, arg2);
}

export function DropIntercepted() {
  return window['go']['main']['App']['DropIntercepted']();
}

export function ForwardIntercepted(arg1) {
  return window['go']['main']['App']['ForwardIntercepted'](arg1);
}

export function GetChromePaths() {
  return window['go']['main']['App']['GetChromePaths']();
}

export function GetExtensionCode(arg1) {
  return window['go']['main']['App']['GetExtensionCode'](arg1);
}

export function GetExtensionFlag(arg1, arg2) {
  return window['go']['main']['App']['GetExtensionFlag'](arg1, arg2);
}

export function GetExtensionLogs(arg1) {
  return window['go']['main']['App']['GetExtensionLogs'](arg1);
}

export function GetExtensionUI(arg1) {
  return window['go']['main']['App']['GetExtensionUI'](arg1);
}

export function GetExtensions() {
  return window['go']['main']['App']['GetExtensions']();
}

export function GetFilters() {
  return window['go']['main']['App']['GetFilters']();
}

export function GetInterceptFlag() {
  return window['go']['main']['App']['GetInterceptFlag']();
}

export function GetIntercepted() {
  return window['go']['main']['App']['GetIntercepted']();
}

export function GetInterceptedQueue() {
  return window['go']['main']['App']['GetInterceptedQueue']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMarasiConfig() {
  return window['go']['main']['App']['GetMarasiConfig']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetProxyItems() {
  return window['go']['main']['App']['GetProxyItems']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetRepeaterRequests(arg1) {
  return window['go']['main']['App']['GetRepeaterRequests'](arg1);
}

export function GetRepeaterTabs() {
  return window['go']['main']['App']['GetRepeaterTabs']();
}

export function GetResponse(arg1) {
  return window['go']['main']['App']['GetResponse'](arg1);
}

export function GetScopeRules() {
  return window['go']['main']['App']['GetScopeRules']();
}

export function GetWaypoints() {
  return window['go']['main']['App']['GetWaypoints']();
}

export function HighlightRow(arg1, arg2) {
  return window['go']['main']['App']['HighlightRow'](arg1, arg2);
}

export function InterceptResponse() {
  return window['go']['main']['App']['InterceptResponse']();
}

export function LinkRequestToRepeater(arg1, arg2) {
  return window['go']['main']['App']['LinkRequestToRepeater'](arg1, arg2);
}

export function LoadExtensions() {
  return window['go']['main']['App']['LoadExtensions']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function Repeat(arg1, arg2, arg3) {
  return window['go']['main']['App']['Repeat'](arg1, arg2, arg3);
}

export function RunExtension(arg1, arg2) {
  return window['go']['main']['App']['RunExtension'](arg1, arg2);
}

export function SetFilters(arg1) {
  return window['go']['main']['App']['SetFilters'](arg1);
}

export function SetFlag(arg1, arg2) {
  return window['go']['main']['App']['SetFlag'](arg1, arg2);
}

export function SetupScratchpad() {
  return window['go']['main']['App']['SetupScratchpad']();
}

export function StartBrowser() {
  return window['go']['main']['App']['StartBrowser']();
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestScopeMatch(arg1) {
  return window['go']['main']['App']['TestScopeMatch'](arg1);
}

export function ToggleFlag(arg1) {
  return window['go']['main']['App']['ToggleFlag'](arg1);
}

export function ToggleIntercept() {
  return window['go']['main']['App']['ToggleIntercept']();
}

export function UninstallExtension(arg1) {
  return window['go']['main']['App']['UninstallExtension'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}

export function UpdateRepeaterEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRepeaterEntry'](arg1, arg2, arg3);
}
