// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {marasi} from '../models';
import {main} from '../models';
import {uuid} from '../models';

export function AddChromePath(arg1:string,arg2:string):Promise<Array<marasi.ChromePathConfig>>;

export function CheckExtensionUpdates():Promise<Record<string, boolean>>;

export function CheckHTTPParse(arg1:string):Promise<string>;

export function CountNotes():Promise<main.Dashboard>;

export function CreateRepeaterEntry(arg1:string,arg2:string):Promise<uuid.UUID>;

export function CreateWaypoint(arg1:string,arg2:string):Promise<void>;

export function DeleteChromePath(arg1:string,arg2:string):Promise<Array<marasi.ChromePathConfig>>;

export function DeleteRepeaterEntry(arg1:uuid.UUID):Promise<void>;

export function DeleteWaypoint(arg1:string):Promise<void>;

export function DoExtender(arg1:string):Promise<void>;

export function DownloadExtension(arg1:string,arg2:boolean):Promise<void>;

export function DropIntercepted():Promise<void>;

export function ForwardIntercepted(arg1:string):Promise<void>;

export function GetChromePaths():Promise<Array<marasi.ChromePathConfig>>;

export function GetExtensionCode(arg1:string):Promise<string>;

export function GetExtensionFlag(arg1:string,arg2:string):Promise<boolean>;

export function GetExtensionLogs(arg1:string):Promise<Array<marasi.ExtensionLog>>;

export function GetExtensionUI(arg1:string):Promise<main.ExtensionUI>;

export function GetExtensions():Promise<Record<string, marasi.Extension>>;

export function GetFilters():Promise<Array<string>>;

export function GetInterceptFlag():Promise<boolean>;

export function GetIntercepted():Promise<main.InterceptedResult>;

export function GetInterceptedQueue():Promise<number>;

export function GetInterfaces():Promise<Array<string>>;

export function GetLogs():Promise<Array<marasi.Log>>;

export function GetMarasiConfig():Promise<main.Config>;

export function GetMetadata(arg1:uuid.UUID):Promise<marasi.Metadata>;

export function GetNote(arg1:uuid.UUID):Promise<string>;

export function GetProxyItems():Promise<Record<uuid.UUID, marasi.Row>>;

export function GetRawDetails(arg1:uuid.UUID):Promise<marasi.Row>;

export function GetRecentProjects():Promise<Array<any>>;

export function GetRepeaterRequests(arg1:uuid.UUID):Promise<Array<marasi.ProxyRequest>>;

export function GetRepeaterTabs():Promise<Array<marasi.Launchpad>>;

export function GetResponse(arg1:uuid.UUID):Promise<marasi.ProxyResponse>;

export function GetScopeRules():Promise<Record<string, any>>;

export function GetWaypoints():Promise<Record<string, string>>;

export function HighlightRow(arg1:uuid.UUID,arg2:number):Promise<void>;

export function InterceptResponse():Promise<void>;

export function LinkRequestToRepeater(arg1:uuid.UUID,arg2:uuid.UUID):Promise<void>;

export function LoadExtensions():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenProject(arg1:string):Promise<string>;

export function Repeat(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RunExtension(arg1:string,arg2:string):Promise<void>;

export function SetFilters(arg1:Array<string>):Promise<void>;

export function SetFlag(arg1:string,arg2:string):Promise<main.Config>;

export function SetupScratchpad():Promise<void>;

export function StartBrowser():Promise<void>;

export function StartProxy(arg1:string,arg2:string):Promise<void>;

export function StopProxy():Promise<void>;

export function TestScopeMatch(arg1:string):Promise<Record<string, any>>;

export function ToggleFlag(arg1:string):Promise<main.Config>;

export function ToggleIntercept():Promise<boolean>;

export function UninstallExtension(arg1:string):Promise<void>;

export function UpdateNote(arg1:uuid.UUID,arg2:string):Promise<void>;

export function UpdateRepeaterEntry(arg1:uuid.UUID,arg2:string,arg3:string):Promise<void>;
